trigger:
  branches:
    include:
      - main  # Ou a branch que deseja monitorar

pool:
  vmImage: 'ubuntu-latest'  # Usa uma VM Linux

steps:
  # Checkout do código
  - task: Checkout@1
    displayName: 'Check out source code'

  # Construir a imagem Docker usando o Dockerfile
  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      command: 'build'
      Dockerfile: 'Dockerfile'  # Localização do Dockerfile no repositório
      #containerRegistry: 'Container Registry'  # O registro de contêiner se necessário (se for publicar a imagem)
      tags: 'webgoat/webgoat:latest'  # Tag da imagem

  # Rodar o contêiner com a imagem criada
  - task: Docker@2
    displayName: 'Run Docker Container'
    inputs:
      command: 'run'
      imageName: 'webgoat/webgoat:latest'  # A imagem criada
      containerName: 'webgoat-container'  # Nome do contêiner
      options: '-d -p 127.0.0.1:8080:8080 -p 127.0.0.1:9090:9090'  # Mapeamento de portas

