trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    container:
      image: openjdk:17-jdk  # Use JDK 17
    steps:
    - script: |
        apt-get update && apt-get install -y sudo  # Instala sudo
        echo "azure_pipelines_sudo ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers  # Configura sudoers
        echo "Building the project with Maven..."
        mvn clean package
      displayName: 'Run Maven Build'

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
