# Integrate Fortify ScanCentral Static AppSec Testing (SAST) into your Azure DevOps pipeline
# The following pipeline variables must be defined before using SAST stage
#   - $_FCLI_DEFAULT_SC_SAST_CLIENT_AUTH_TOKEN
#   - $_FCLI_DEFAULT_SSC_USER
#   - $_FCLI_DEFAULT_SSC_PASSWORD
#   - $_FCLI_DEFAULT_SSC_CI_TOKEN
#   - $_FCLI_DEFAULT_SSC_URL
#   - $_SSC_APP_VERSION_ID

# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none
stages:
- stage: Build
  jobs:
    - job: Build
      displayName: Building IWA Project
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false