trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Checkout do código
  - checkout: self

  # Construir a imagem Docker
  - script: |
      docker build -t webgoat/webgoat:latest -f Dockerfile .
    displayName: 'Build Docker Image'

  # Rodar o contêiner com a imagem construída
  - script: |
      docker run -d -p 127.0.0.1:8080:8080 -p 127.0.0.1:9090:9090 webgoat/webgoat:latest
    displayName: 'Run Docker Container'
