trigger:
  branches:
    include:
      - main  # Ajuste para a branch que deseja monitorar

pool:
  vmImage: 'ubuntu-latest'  # Usando uma VM com Ubuntu

steps:
  # Checkout do código-fonte
  - task: Checkout@1
    displayName: 'Check out source code'

  # Tornar o script executável
  - script: |
      chmod +x ./build_docker.sh
    displayName: 'Make build_docker.sh executable'

  # Executar o script para construir e rodar o contêiner Docker
  - script: |
      ./build_docker.sh
    displayName: 'Build and Run Docker Container'
